Get categories
alkemyTech/OT117-CLIENT pull request #15
Opened 2021-12-21 00:12 UTC by luchh9

**En backoffice:**

- Se rendereaban 3 categorias estaticas guardadas en una variable

- Aplique los servicios http para que obtenga todas las categorias de la API y las renderice

**faltan las funcionalidades (add, delete, put)**

2021-12-24 14:52 UTC, sntmsc requested changes

2021-12-24 14:52 UTC, sntmsc commented on src/Services/categoriesServices.js
> +const baseURL = "http://ongapi.alkemy.org/api/categories";
Quedó el enlace al endpoint hardcodeado, tendría que estar funcionando con process.env.REACT_APP_BASE_URL_CATEGORIES

2021-12-24 20:22 UTC, Axel-Nieto reviewed
creo que solo tenes que modificar el enlace al endpoint y sacar el console.log que usas para debuggear

2021-12-24 20:22 UTC, Axel-Nieto commented on src/Services/categoriesServices.js
> +    return data.data;
quitale los console.log que sirvan para debug

2021-12-28 20:09 UTC, luisalfonso099 approved these changes

2021-12-29 01:30 UTC, Axel-Nieto approved these changes

2021-12-29 07:40 UTC, closed without merging